//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbComesticEntities : DbContext
    {
        public DbComesticEntities()
            : base("name=DbComesticEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbBrand> tbBrands { get; set; }
        public virtual DbSet<tbCart> tbCarts { get; set; }
        public virtual DbSet<tbCategory> tbCategories { get; set; }
        public virtual DbSet<tbContact> tbContacts { get; set; }
        public virtual DbSet<tbCustomer> tbCustomers { get; set; }
        public virtual DbSet<tbNation> tbNations { get; set; }
        public virtual DbSet<tbOrderDetail> tbOrderDetails { get; set; }
        public virtual DbSet<tbOrder> tbOrders { get; set; }
        public virtual DbSet<tbProduct> tbProducts { get; set; }
        public virtual DbSet<tbReviewer> tbReviewers { get; set; }
        public virtual DbSet<tbUser> tbUsers { get; set; }
    }
}
