//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCart
    {
        public long Id_Cart { get; set; }
        public Nullable<long> Id_Customer { get; set; }
        public string Image_Product { get; set; }
        public string Name_Product { get; set; }
        public Nullable<long> Id_Product { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> UnitsTotal { get; set; }
    
        public virtual tbCustomer tbCustomer { get; set; }
        public virtual tbProduct tbProduct { get; set; }
    }
}
