//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbContact
    {
        public long Id_Contact { get; set; }
        public string Name_Contact { get; set; }
        public string Email_Contact { get; set; }
        public string Subject_Contact { get; set; }
        public string Content_Contatc { get; set; }
    }
}
