//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbOrderDetail
    {
        public long Id_OrderDetail { get; set; }
        public Nullable<long> Id_Order { get; set; }
        public Nullable<long> Id_Product { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price_OrderDetail { get; set; }
    
        public virtual tbOrder tbOrder { get; set; }
        public virtual tbProduct tbProduct { get; set; }
    }
}
